### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by fdstevex** [akkyie/WAKit#42]
Hi - I'm interested in using WAKit to make a QuickLook extension for .wasm files, but I don't see a LICENSE file in the project so it's not clear whether that's allowed. 

Could you please add a LICENSE file?  Preferably a non-restrictive license if you're ok with it being reused.  Thanks.

**Comment by MaxDesiatov** [comment]
Hey @akkyie, I'm interested in contributing to this awesome project, could you provide an update on the license please? Thank you!

**Comment by akkyie** [comment]
@fdstevex @MaxDesiatov 
Hi guys, thank you pinging me and deeply apologize for the late response.
I _really_ don't know why I missed this issue…
It's now under MIT as usual.

This was nothing more than a hobby project during my college days, which I couldn't eventually get to work completely. I hope it helps you if it can, however!
(BTW I'm also exciting about the recent progress of swift-wasm!)
